/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appconta;

/**
 *
 * @author José
 */
public class AppConta extends javax.swing.JFrame {

    /**
     * Creates new form AppConta
     */
    public AppConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_IZQ = new javax.swing.JPanel();
        Bot_Req = new javax.swing.JLabel();
        Bot_Tarj = new javax.swing.JLabel();
        Bot_Tasa = new javax.swing.JLabel();
        Bot_HojaC = new javax.swing.JLabel();
        EspacioEnBlanco = new javax.swing.JLabel();
        Bot_HojaC1 = new javax.swing.JLabel();
        Pantallas = new javax.swing.JPanel();
        Req = new javax.swing.JPanel();
        LineaArriba_Req = new javax.swing.JPanel();
        SubT_Req = new javax.swing.JLabel();
        TF_NumReq_Req = new javax.swing.JTextField();
        Lbl_NumReq_Req = new javax.swing.JLabel();
        Lbl_Fecha_Req = new javax.swing.JLabel();
        TF_Fecha_Req = new javax.swing.JTextField();
        Lbl_Departamento_Req = new javax.swing.JLabel();
        TF_Departamento_Req = new javax.swing.JTextField();
        Lbl_NumPedido_Req = new javax.swing.JLabel();
        TF_NumPedido_Req = new javax.swing.JTextField();
        T_Req = new javax.swing.JScrollPane();
        TablaReq = new javax.swing.JTable();
        Bot_Add_Req = new javax.swing.JButton();
        Bot_Elim_Req = new javax.swing.JButton();
        Bot_Mod_Req = new javax.swing.JButton();
        Bot_Sig_Req = new javax.swing.JButton();
        TF_Departamento_Req1 = new javax.swing.JTextField();
        Lbl_Departamento_Req1 = new javax.swing.JLabel();
        TF_Departamento_Req2 = new javax.swing.JTextField();
        Lbl_Departamento_Req2 = new javax.swing.JLabel();
        TarjetaT = new javax.swing.JPanel();
        LineaArriba_TarjetaT = new javax.swing.JPanel();
        SubT_TarjetaT = new javax.swing.JLabel();
        TF_NomEmp_TT = new javax.swing.JTextField();
        Lbl_Nom_Emp_TT = new javax.swing.JLabel();
        Lbl_NumNom_TT = new javax.swing.JLabel();
        TF_NumNom_TT = new javax.swing.JTextField();
        Lbl_NumPed_TT = new javax.swing.JLabel();
        Num_Ped_TT = new javax.swing.JTextField();
        Lbl_Mes_TT = new javax.swing.JLabel();
        TF_Mes_TT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaReq1 = new javax.swing.JTable();
        Bot_Add_TT = new javax.swing.JButton();
        Bot_Elim_TT = new javax.swing.JButton();
        Bot_Mod_TT = new javax.swing.JButton();
        Bot_Sig_TT = new javax.swing.JButton();
        TasaGIF = new javax.swing.JPanel();
        LineaArriba_GIF = new javax.swing.JPanel();
        SubT_GIF = new javax.swing.JLabel();
        TF_GIFP_GIF = new javax.swing.JTextField();
        Lbl_GIF_GIF = new javax.swing.JLabel();
        Lbl_BaseA_GIF = new javax.swing.JLabel();
        TF_BaseA_GIF = new javax.swing.JTextField();
        Bot_Sig_GIF = new javax.swing.JButton();
        HojaCosto = new javax.swing.JPanel();
        LineaArriba_HC = new javax.swing.JPanel();
        SubT_HC = new javax.swing.JLabel();
        Lbl_ResMD_HC = new javax.swing.JLabel();
        Lbl_ResMod_HC = new javax.swing.JLabel();
        Lbl_ResGIF_HC = new javax.swing.JLabel();
        Lbl_ResCU = new javax.swing.JLabel();
        Lbl_ResCT = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_MD_HC = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tabla_GIF_HC = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla_MOD_HC = new javax.swing.JTable();
        Lbl_SubMD_HC = new javax.swing.JLabel();
        Lbl_SubMOD_HC = new javax.swing.JLabel();
        Lbl_SubGIF_HC = new javax.swing.JLabel();
        Lbl_Cliente_HC = new javax.swing.JLabel();
        Lbl_NumOrd_HC = new javax.swing.JLabel();
        Lbl_Desc_HC = new javax.swing.JLabel();
        Lbl_Cant_HC = new javax.swing.JLabel();
        Lbl_FechaIn_HC = new javax.swing.JLabel();
        Lbl_FechaTe_HC = new javax.swing.JLabel();
        Lbl_ClienteDer_HC = new javax.swing.JLabel();
        Lbl_NumOrdDer_HC = new javax.swing.JLabel();
        Lbl_DescDer_HC = new javax.swing.JLabel();
        Lbl_CantDer_HC = new javax.swing.JLabel();
        Lbl_FechaInDer_HC = new javax.swing.JLabel();
        Lbl_FechaTeDer_HC = new javax.swing.JLabel();
        Panel_CT_HC = new javax.swing.JPanel();
        Lbl_CTTabla_HC = new javax.swing.JLabel();
        Lbl_CGIF_HC = new javax.swing.JLabel();
        Lbl_CMD_HC = new javax.swing.JLabel();
        Lbl_CMOD_HC = new javax.swing.JLabel();
        Lbl_ResMDDer_HC = new javax.swing.JLabel();
        Lbl_ResMODDer_HC = new javax.swing.JLabel();
        Lbl_ResGIFDer_HC = new javax.swing.JLabel();
        Lbl_ResCTDer_HC = new javax.swing.JLabel();
        Lbl_ResCUDer_HC = new javax.swing.JLabel();
        InDatos = new javax.swing.JPanel();
        LineaArriba_InD = new javax.swing.JPanel();
        SubT_InD = new javax.swing.JLabel();
        TF_Cliente_InD = new javax.swing.JTextField();
        Lbl_Cliente_InD = new javax.swing.JLabel();
        Lbl_DescP_InD = new javax.swing.JLabel();
        TF_DescP_InD = new javax.swing.JTextField();
        Bot_Sig_InD = new javax.swing.JButton();
        Lbl_FechaIn_InD = new javax.swing.JLabel();
        TF_FechaIn_InD = new javax.swing.JTextField();
        Lbl_FechaTe_InD = new javax.swing.JLabel();
        TF_FechaTe_InD = new javax.swing.JTextField();
        Lbl_Cant_InD = new javax.swing.JLabel();
        TF_Cant_InD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Contable");
        setName(""); // NOI18N

        Menu_IZQ.setBackground(new java.awt.Color(12, 45, 72));

        Bot_Req.setBackground(new java.awt.Color(213, 225, 234));
        Bot_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Bot_Req.setForeground(new java.awt.Color(213, 225, 234));
        Bot_Req.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bot_Req.setText("Requisición de materiales");
        Bot_Req.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bot_ReqMouseClicked(evt);
            }
        });

        Bot_Tarj.setBackground(new java.awt.Color(213, 225, 234));
        Bot_Tarj.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Bot_Tarj.setForeground(new java.awt.Color(213, 225, 234));
        Bot_Tarj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bot_Tarj.setText("Tarjetas de tiempo");

        Bot_Tasa.setBackground(new java.awt.Color(213, 225, 234));
        Bot_Tasa.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Bot_Tasa.setForeground(new java.awt.Color(213, 225, 234));
        Bot_Tasa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bot_Tasa.setText("Tasa predeterminada GIF");

        Bot_HojaC.setBackground(new java.awt.Color(213, 225, 234));
        Bot_HojaC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Bot_HojaC.setForeground(new java.awt.Color(213, 225, 234));
        Bot_HojaC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bot_HojaC.setText("Hoja de costos");

        EspacioEnBlanco.setForeground(new java.awt.Color(255, 255, 255));
        EspacioEnBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EspacioEnBlancoMouseClicked(evt);
            }
        });

        Bot_HojaC1.setBackground(new java.awt.Color(213, 225, 234));
        Bot_HojaC1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Bot_HojaC1.setForeground(new java.awt.Color(213, 225, 234));
        Bot_HojaC1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bot_HojaC1.setText("Inserción de datos");

        javax.swing.GroupLayout Menu_IZQLayout = new javax.swing.GroupLayout(Menu_IZQ);
        Menu_IZQ.setLayout(Menu_IZQLayout);
        Menu_IZQLayout.setHorizontalGroup(
            Menu_IZQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_IZQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_IZQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bot_Tarj, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Bot_Tasa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Bot_HojaC, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(EspacioEnBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bot_HojaC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Menu_IZQLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bot_HojaC, Bot_Req, Bot_Tarj, Bot_Tasa});

        Menu_IZQLayout.setVerticalGroup(
            Menu_IZQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_IZQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EspacioEnBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_Tarj, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_Tasa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_HojaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_HojaC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        Menu_IZQLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bot_HojaC, Bot_Req, Bot_Tarj, Bot_Tasa});

        getContentPane().add(Menu_IZQ, java.awt.BorderLayout.LINE_START);

        Pantallas.setBackground(new java.awt.Color(255, 255, 255));
        Pantallas.setLayout(new java.awt.CardLayout());

        Req.setBackground(new java.awt.Color(66, 71, 74));

        LineaArriba_Req.setBackground(new java.awt.Color(80, 118, 156));

        SubT_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        SubT_Req.setForeground(new java.awt.Color(228, 228, 233));
        SubT_Req.setText("Requisición de materiales");

        javax.swing.GroupLayout LineaArriba_ReqLayout = new javax.swing.GroupLayout(LineaArriba_Req);
        LineaArriba_Req.setLayout(LineaArriba_ReqLayout);
        LineaArriba_ReqLayout.setHorizontalGroup(
            LineaArriba_ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LineaArriba_ReqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LineaArriba_ReqLayout.setVerticalGroup(
            LineaArriba_ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LineaArriba_ReqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_Req, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        TF_NumReq_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_NumReq_Req.setToolTipText("");

        Lbl_NumReq_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_NumReq_Req.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumReq_Req.setText("Número de requisición");

        Lbl_Fecha_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Fecha_Req.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Fecha_Req.setText("Fecha");

        TF_Fecha_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Fecha_Req.setToolTipText("");

        Lbl_Departamento_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Departamento_Req.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Departamento_Req.setText("Departamento");

        TF_Departamento_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Departamento_Req.setToolTipText("");

        Lbl_NumPedido_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_NumPedido_Req.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumPedido_Req.setText("Número de pedido");

        TF_NumPedido_Req.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_NumPedido_Req.setToolTipText("");

        TablaReq.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        TablaReq.setForeground(new java.awt.Color(0, 0, 0));
        TablaReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripción", "CU", "CT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaReq.setToolTipText("");
        TablaReq.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaReq.setName(""); // NOI18N
        TablaReq.setRowHeight(25);
        TablaReq.setSelectionBackground(new java.awt.Color(80, 118, 156));
        T_Req.setViewportView(TablaReq);

        Bot_Add_Req.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Add_Req.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Add_Req.setText("Añadir");

        Bot_Elim_Req.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Elim_Req.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Elim_Req.setText("Eliminar");

        Bot_Mod_Req.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Mod_Req.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Mod_Req.setText("Modificar");

        Bot_Sig_Req.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Sig_Req.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Sig_Req.setText("Siguiente");
        Bot_Sig_Req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_Sig_ReqActionPerformed(evt);
            }
        });

        TF_Departamento_Req1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Departamento_Req1.setToolTipText("");

        Lbl_Departamento_Req1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Departamento_Req1.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Departamento_Req1.setText("Recibido por");

        TF_Departamento_Req2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Departamento_Req2.setToolTipText("");

        Lbl_Departamento_Req2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Departamento_Req2.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Departamento_Req2.setText("Entregado por");

        javax.swing.GroupLayout ReqLayout = new javax.swing.GroupLayout(Req);
        Req.setLayout(ReqLayout);
        ReqLayout.setHorizontalGroup(
            ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LineaArriba_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ReqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqLayout.createSequentialGroup()
                        .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_NumReq_Req, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(TF_NumReq_Req))
                            .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_Fecha_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Fecha_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_Departamento_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Departamento_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_NumPedido_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_NumPedido_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(T_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bot_Mod_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bot_Elim_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bot_Add_Req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReqLayout.createSequentialGroup()
                        .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_Departamento_Req1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_Departamento_Req1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_Departamento_Req2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_Departamento_Req2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bot_Sig_Req)))
                .addContainerGap())
        );
        ReqLayout.setVerticalGroup(
            ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReqLayout.createSequentialGroup()
                .addComponent(LineaArriba_Req, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ReqLayout.createSequentialGroup()
                            .addComponent(Lbl_NumReq_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_NumReq_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_Fecha_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_Fecha_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_Departamento_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_Departamento_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_NumPedido_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_NumPedido_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(T_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(ReqLayout.createSequentialGroup()
                        .addComponent(Bot_Add_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot_Elim_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot_Mod_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot_Sig_Req, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReqLayout.createSequentialGroup()
                        .addComponent(Lbl_Departamento_Req1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Departamento_Req1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReqLayout.createSequentialGroup()
                        .addComponent(Lbl_Departamento_Req2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Departamento_Req2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );

        Pantallas.add(Req, "ReqMat");

        TarjetaT.setBackground(new java.awt.Color(66, 71, 74));

        LineaArriba_TarjetaT.setBackground(new java.awt.Color(80, 118, 156));
        LineaArriba_TarjetaT.setInheritsPopupMenu(true);

        SubT_TarjetaT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        SubT_TarjetaT.setForeground(new java.awt.Color(228, 228, 233));
        SubT_TarjetaT.setText("Tarjeta de tiempo");

        javax.swing.GroupLayout LineaArriba_TarjetaTLayout = new javax.swing.GroupLayout(LineaArriba_TarjetaT);
        LineaArriba_TarjetaT.setLayout(LineaArriba_TarjetaTLayout);
        LineaArriba_TarjetaTLayout.setHorizontalGroup(
            LineaArriba_TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LineaArriba_TarjetaTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_TarjetaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LineaArriba_TarjetaTLayout.setVerticalGroup(
            LineaArriba_TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LineaArriba_TarjetaTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_TarjetaT, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        TF_NomEmp_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_NomEmp_TT.setToolTipText("");

        Lbl_Nom_Emp_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Nom_Emp_TT.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Nom_Emp_TT.setText("Nombre del empleado");

        Lbl_NumNom_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_NumNom_TT.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumNom_TT.setText("Número de nómina");

        TF_NumNom_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_NumNom_TT.setToolTipText("");

        Lbl_NumPed_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_NumPed_TT.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumPed_TT.setText("Número de pedido");

        Num_Ped_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        Num_Ped_TT.setToolTipText("");

        Lbl_Mes_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Mes_TT.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Mes_TT.setText("Mes");

        TF_Mes_TT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Mes_TT.setToolTipText("");

        TablaReq1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        TablaReq1.setForeground(new java.awt.Color(0, 0, 0));
        TablaReq1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Día", "Tiempo total (horas)", "Tasa por hora", "Costo total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaReq1.setToolTipText("");
        TablaReq1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaReq1.setName(""); // NOI18N
        TablaReq1.setRowHeight(25);
        TablaReq1.setSelectionBackground(new java.awt.Color(80, 118, 156));
        jScrollPane2.setViewportView(TablaReq1);

        Bot_Add_TT.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Add_TT.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Add_TT.setText("Añadir");

        Bot_Elim_TT.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Elim_TT.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Elim_TT.setText("Eliminar");

        Bot_Mod_TT.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Mod_TT.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Mod_TT.setText("Modificar");

        Bot_Sig_TT.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Sig_TT.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Sig_TT.setText("Siguiente");

        javax.swing.GroupLayout TarjetaTLayout = new javax.swing.GroupLayout(TarjetaT);
        TarjetaT.setLayout(TarjetaTLayout);
        TarjetaTLayout.setHorizontalGroup(
            TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_Nom_Emp_TT, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addComponent(TF_NomEmp_TT))
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_NumNom_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_NumNom_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_NumPed_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Num_Ped_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_Mes_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_Mes_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Bot_Mod_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bot_Elim_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bot_Add_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Bot_Sig_TT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LineaArriba_TarjetaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TarjetaTLayout.setVerticalGroup(
            TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaTLayout.createSequentialGroup()
                .addComponent(LineaArriba_TarjetaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TarjetaTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(TarjetaTLayout.createSequentialGroup()
                            .addComponent(Lbl_Nom_Emp_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_NomEmp_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_NumNom_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_NumNom_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_NumPed_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Num_Ped_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Lbl_Mes_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TF_Mes_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(TarjetaTLayout.createSequentialGroup()
                        .addComponent(Bot_Add_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot_Elim_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bot_Mod_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(Bot_Sig_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        Pantallas.add(TarjetaT, "TarjetaT");

        TasaGIF.setBackground(new java.awt.Color(66, 71, 74));

        LineaArriba_GIF.setBackground(new java.awt.Color(80, 118, 156));

        SubT_GIF.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        SubT_GIF.setForeground(new java.awt.Color(228, 228, 233));
        SubT_GIF.setText("Tasa predeterminada GIF");

        javax.swing.GroupLayout LineaArriba_GIFLayout = new javax.swing.GroupLayout(LineaArriba_GIF);
        LineaArriba_GIF.setLayout(LineaArriba_GIFLayout);
        LineaArriba_GIFLayout.setHorizontalGroup(
            LineaArriba_GIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LineaArriba_GIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_GIF, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE))
        );
        LineaArriba_GIFLayout.setVerticalGroup(
            LineaArriba_GIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LineaArriba_GIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_GIF, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        TF_GIFP_GIF.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_GIFP_GIF.setToolTipText("");

        Lbl_GIF_GIF.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_GIF_GIF.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_GIF_GIF.setText("GIF totales presupuestados");

        Lbl_BaseA_GIF.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_BaseA_GIF.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_BaseA_GIF.setText("Base de aplicación");

        TF_BaseA_GIF.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_BaseA_GIF.setToolTipText("");

        Bot_Sig_GIF.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Sig_GIF.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Sig_GIF.setText("Siguiente");

        javax.swing.GroupLayout TasaGIFLayout = new javax.swing.GroupLayout(TasaGIF);
        TasaGIF.setLayout(TasaGIFLayout);
        TasaGIFLayout.setHorizontalGroup(
            TasaGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LineaArriba_GIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TasaGIFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TasaGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TasaGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_GIF_GIF, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addComponent(TF_GIFP_GIF))
                    .addGroup(TasaGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Lbl_BaseA_GIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TF_BaseA_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bot_Sig_GIF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TasaGIFLayout.setVerticalGroup(
            TasaGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasaGIFLayout.createSequentialGroup()
                .addComponent(LineaArriba_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_GIF_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_GIFP_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_BaseA_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_BaseA_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bot_Sig_GIF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        Pantallas.add(TasaGIF, "TasaGIF");

        HojaCosto.setBackground(new java.awt.Color(66, 71, 74));

        LineaArriba_HC.setBackground(new java.awt.Color(80, 118, 156));

        SubT_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        SubT_HC.setForeground(new java.awt.Color(228, 228, 233));
        SubT_HC.setText("Hoja de costos");

        javax.swing.GroupLayout LineaArriba_HCLayout = new javax.swing.GroupLayout(LineaArriba_HC);
        LineaArriba_HC.setLayout(LineaArriba_HCLayout);
        LineaArriba_HCLayout.setHorizontalGroup(
            LineaArriba_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LineaArriba_HCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LineaArriba_HCLayout.setVerticalGroup(
            LineaArriba_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LineaArriba_HCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_HC, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        Lbl_ResMD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResMD_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResMD_HC.setText("Materiales directos");

        Lbl_ResMod_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResMod_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResMod_HC.setText("Mano de obra directa");

        Lbl_ResGIF_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResGIF_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResGIF_HC.setText("Gastos indirectos de fabricación");

        Lbl_ResCU.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResCU.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResCU.setText("Costo unitario");

        Lbl_ResCT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResCT.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResCT.setText("Costos totales");

        Tabla_MD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Tabla_MD_HC.setForeground(new java.awt.Color(0, 0, 0));
        Tabla_MD_HC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Fecha", "# Req", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_MD_HC.setToolTipText("");
        Tabla_MD_HC.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tabla_MD_HC.setName(""); // NOI18N
        Tabla_MD_HC.setRowHeight(25);
        Tabla_MD_HC.setSelectionBackground(new java.awt.Color(80, 118, 156));
        jScrollPane5.setViewportView(Tabla_MD_HC);

        Tabla_GIF_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Tabla_GIF_HC.setForeground(new java.awt.Color(0, 0, 0));
        Tabla_GIF_HC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Horas", "Tasa", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_GIF_HC.setToolTipText("");
        Tabla_GIF_HC.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tabla_GIF_HC.setName(""); // NOI18N
        Tabla_GIF_HC.setRowHeight(25);
        Tabla_GIF_HC.setSelectionBackground(new java.awt.Color(80, 118, 156));
        jScrollPane7.setViewportView(Tabla_GIF_HC);

        Tabla_MOD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        Tabla_MOD_HC.setForeground(new java.awt.Color(0, 0, 0));
        Tabla_MOD_HC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "# Tarjeta", "Horas", "Tasa", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_MOD_HC.setToolTipText("");
        Tabla_MOD_HC.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tabla_MOD_HC.setName(""); // NOI18N
        Tabla_MOD_HC.setRowHeight(25);
        Tabla_MOD_HC.setSelectionBackground(new java.awt.Color(80, 118, 156));
        jScrollPane6.setViewportView(Tabla_MOD_HC);

        Lbl_SubMD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        Lbl_SubMD_HC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_SubMD_HC.setText("Materiales directos");

        Lbl_SubMOD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        Lbl_SubMOD_HC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_SubMOD_HC.setText("Mano de obra directa");

        Lbl_SubGIF_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        Lbl_SubGIF_HC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_SubGIF_HC.setText("GIF");

        Lbl_Cliente_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_Cliente_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Cliente_HC.setText("Cliente");

        Lbl_NumOrd_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_NumOrd_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumOrd_HC.setText("Órden número");

        Lbl_Desc_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_Desc_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Desc_HC.setText("Descripción");

        Lbl_Cant_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_Cant_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Cant_HC.setText("Cantidad");

        Lbl_FechaIn_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_FechaIn_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaIn_HC.setText("Fecha de inicio");

        Lbl_FechaTe_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_FechaTe_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaTe_HC.setText("Fecha de terminación");

        Lbl_ClienteDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ClienteDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ClienteDer_HC.setText("...");

        Lbl_NumOrdDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_NumOrdDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_NumOrdDer_HC.setText("...");

        Lbl_DescDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_DescDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_DescDer_HC.setText("...");

        Lbl_CantDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_CantDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_CantDer_HC.setText("...");

        Lbl_FechaInDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_FechaInDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaInDer_HC.setText("...");

        Lbl_FechaTeDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_FechaTeDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaTeDer_HC.setText("...");

        Lbl_CTTabla_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_CTTabla_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_CTTabla_HC.setText("Costo total");

        Lbl_CGIF_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_CGIF_HC.setForeground(new java.awt.Color(228, 228, 233));

        Lbl_CMD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_CMD_HC.setForeground(new java.awt.Color(228, 228, 233));

        Lbl_CMOD_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_CMOD_HC.setForeground(new java.awt.Color(228, 228, 233));

        javax.swing.GroupLayout Panel_CT_HCLayout = new javax.swing.GroupLayout(Panel_CT_HC);
        Panel_CT_HC.setLayout(Panel_CT_HCLayout);
        Panel_CT_HCLayout.setHorizontalGroup(
            Panel_CT_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CT_HCLayout.createSequentialGroup()
                .addComponent(Lbl_CTTabla_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_CMD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(Lbl_CMOD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(Lbl_CGIF_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_CT_HCLayout.setVerticalGroup(
            Panel_CT_HCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbl_CTTabla_HC, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(Lbl_CMD_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Lbl_CMOD_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Lbl_CGIF_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Lbl_ResMDDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResMDDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResMDDer_HC.setText("...");

        Lbl_ResMODDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResMODDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResMODDer_HC.setText("...");

        Lbl_ResGIFDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResGIFDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResGIFDer_HC.setText("...");

        Lbl_ResCTDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResCTDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResCTDer_HC.setText("...");

        Lbl_ResCUDer_HC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        Lbl_ResCUDer_HC.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_ResCUDer_HC.setText("...");

        javax.swing.GroupLayout HojaCostoLayout = new javax.swing.GroupLayout(HojaCosto);
        HojaCosto.setLayout(HojaCostoLayout);
        HojaCostoLayout.setHorizontalGroup(
            HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LineaArriba_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HojaCostoLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_Cliente_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_NumOrd_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_Cant_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_Desc_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_FechaTe_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_FechaIn_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_ClienteDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_NumOrdDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_CantDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_DescDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_FechaTeDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbl_FechaInDer_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Panel_CT_HC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HojaCostoLayout.createSequentialGroup()
                                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lbl_SubMD_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Lbl_SubMOD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(HojaCostoLayout.createSequentialGroup()
                                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_ResMD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_ResGIF_HC)
                                    .addComponent(Lbl_ResMod_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_ResCU, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_ResCT, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lbl_ResMDDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_ResMODDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_ResCTDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_ResGIFDer_HC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_ResCUDer_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_SubGIF_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        HojaCostoLayout.setVerticalGroup(
            HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HojaCostoLayout.createSequentialGroup()
                .addComponent(LineaArriba_HC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addComponent(Lbl_Cliente_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_NumOrd_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Desc_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_Cant_HC)
                        .addGap(3, 3, 3)
                        .addComponent(Lbl_FechaIn_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_FechaTe_HC))
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addComponent(Lbl_ClienteDer_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_NumOrdDer_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_DescDer_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_CantDer_HC)
                        .addGap(3, 3, 3)
                        .addComponent(Lbl_FechaInDer_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_FechaTeDer_HC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addComponent(Lbl_SubGIF_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_SubMOD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SubMD_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_CT_HC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(HojaCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addComponent(Lbl_ResMD_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResMod_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResGIF_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResCU))
                    .addGroup(HojaCostoLayout.createSequentialGroup()
                        .addComponent(Lbl_ResMDDer_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResMODDer_HC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResGIFDer_HC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResCTDer_HC)
                        .addGap(3, 3, 3)
                        .addComponent(Lbl_ResCUDer_HC)))
                .addGap(52, 52, 52))
        );

        Pantallas.add(HojaCosto, "HojaCosto");

        InDatos.setBackground(new java.awt.Color(66, 71, 74));

        LineaArriba_InD.setBackground(new java.awt.Color(80, 118, 156));

        SubT_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        SubT_InD.setForeground(new java.awt.Color(228, 228, 233));
        SubT_InD.setText("Inserción de datos");

        javax.swing.GroupLayout LineaArriba_InDLayout = new javax.swing.GroupLayout(LineaArriba_InD);
        LineaArriba_InD.setLayout(LineaArriba_InDLayout);
        LineaArriba_InDLayout.setHorizontalGroup(
            LineaArriba_InDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LineaArriba_InDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_InD, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE))
        );
        LineaArriba_InDLayout.setVerticalGroup(
            LineaArriba_InDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LineaArriba_InDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubT_InD, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        TF_Cliente_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Cliente_InD.setToolTipText("");

        Lbl_Cliente_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Cliente_InD.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Cliente_InD.setText("Cliente");

        Lbl_DescP_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_DescP_InD.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_DescP_InD.setText("Descripción del pedido");

        TF_DescP_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_DescP_InD.setToolTipText("");

        Bot_Sig_InD.setBackground(new java.awt.Color(12, 45, 72));
        Bot_Sig_InD.setForeground(new java.awt.Color(228, 228, 233));
        Bot_Sig_InD.setText("Siguiente");

        Lbl_FechaIn_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_FechaIn_InD.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaIn_InD.setText("Fecha de inicio");

        TF_FechaIn_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_FechaIn_InD.setToolTipText("");

        Lbl_FechaTe_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_FechaTe_InD.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_FechaTe_InD.setText("Fecha de terminación");

        TF_FechaTe_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_FechaTe_InD.setToolTipText("");

        Lbl_Cant_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Lbl_Cant_InD.setForeground(new java.awt.Color(228, 228, 233));
        Lbl_Cant_InD.setText("Cantidad");

        TF_Cant_InD.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        TF_Cant_InD.setToolTipText("");

        javax.swing.GroupLayout InDatosLayout = new javax.swing.GroupLayout(InDatos);
        InDatos.setLayout(InDatosLayout);
        InDatosLayout.setHorizontalGroup(
            InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LineaArriba_InD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InDatosLayout.createSequentialGroup()
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_Cliente_InD, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(TF_Cliente_InD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_FechaIn_InD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_FechaIn_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_Cant_InD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_Cant_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InDatosLayout.createSequentialGroup()
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_DescP_InD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_DescP_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_FechaTe_InD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF_FechaTe_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Bot_Sig_InD))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        InDatosLayout.setVerticalGroup(
            InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InDatosLayout.createSequentialGroup()
                .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InDatosLayout.createSequentialGroup()
                        .addComponent(LineaArriba_InD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InDatosLayout.createSequentialGroup()
                                .addComponent(Lbl_Cliente_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_Cliente_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InDatosLayout.createSequentialGroup()
                                .addComponent(Lbl_FechaIn_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_FechaIn_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InDatosLayout.createSequentialGroup()
                                .addComponent(Lbl_Cant_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_Cant_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_DescP_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_DescP_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InDatosLayout.createSequentialGroup()
                        .addComponent(Lbl_FechaTe_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_FechaTe_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Bot_Sig_InD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        Pantallas.add(InDatos, "InDatos");

        getContentPane().add(Pantallas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot_ReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bot_ReqMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bot_ReqMouseClicked

    private void EspacioEnBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EspacioEnBlancoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioEnBlancoMouseClicked

    private void Bot_Sig_ReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_Sig_ReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot_Sig_ReqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_Add_Req;
    private javax.swing.JButton Bot_Add_TT;
    private javax.swing.JButton Bot_Elim_Req;
    private javax.swing.JButton Bot_Elim_TT;
    private javax.swing.JLabel Bot_HojaC;
    private javax.swing.JLabel Bot_HojaC1;
    private javax.swing.JButton Bot_Mod_Req;
    private javax.swing.JButton Bot_Mod_TT;
    private javax.swing.JLabel Bot_Req;
    private javax.swing.JButton Bot_Sig_GIF;
    private javax.swing.JButton Bot_Sig_InD;
    private javax.swing.JButton Bot_Sig_Req;
    private javax.swing.JButton Bot_Sig_TT;
    private javax.swing.JLabel Bot_Tarj;
    private javax.swing.JLabel Bot_Tasa;
    private javax.swing.JLabel EspacioEnBlanco;
    private javax.swing.JPanel HojaCosto;
    private javax.swing.JPanel InDatos;
    private javax.swing.JLabel Lbl_BaseA_GIF;
    private javax.swing.JLabel Lbl_CGIF_HC;
    private javax.swing.JLabel Lbl_CMD_HC;
    private javax.swing.JLabel Lbl_CMOD_HC;
    private javax.swing.JLabel Lbl_CTTabla_HC;
    private javax.swing.JLabel Lbl_CantDer_HC;
    private javax.swing.JLabel Lbl_Cant_HC;
    private javax.swing.JLabel Lbl_Cant_InD;
    private javax.swing.JLabel Lbl_ClienteDer_HC;
    private javax.swing.JLabel Lbl_Cliente_HC;
    private javax.swing.JLabel Lbl_Cliente_InD;
    private javax.swing.JLabel Lbl_Departamento_Req;
    private javax.swing.JLabel Lbl_Departamento_Req1;
    private javax.swing.JLabel Lbl_Departamento_Req2;
    private javax.swing.JLabel Lbl_DescDer_HC;
    private javax.swing.JLabel Lbl_DescP_InD;
    private javax.swing.JLabel Lbl_Desc_HC;
    private javax.swing.JLabel Lbl_FechaInDer_HC;
    private javax.swing.JLabel Lbl_FechaIn_HC;
    private javax.swing.JLabel Lbl_FechaIn_InD;
    private javax.swing.JLabel Lbl_FechaTeDer_HC;
    private javax.swing.JLabel Lbl_FechaTe_HC;
    private javax.swing.JLabel Lbl_FechaTe_InD;
    private javax.swing.JLabel Lbl_Fecha_Req;
    private javax.swing.JLabel Lbl_GIF_GIF;
    private javax.swing.JLabel Lbl_Mes_TT;
    private javax.swing.JLabel Lbl_Nom_Emp_TT;
    private javax.swing.JLabel Lbl_NumNom_TT;
    private javax.swing.JLabel Lbl_NumOrdDer_HC;
    private javax.swing.JLabel Lbl_NumOrd_HC;
    private javax.swing.JLabel Lbl_NumPed_TT;
    private javax.swing.JLabel Lbl_NumPedido_Req;
    private javax.swing.JLabel Lbl_NumReq_Req;
    private javax.swing.JLabel Lbl_ResCT;
    private javax.swing.JLabel Lbl_ResCTDer_HC;
    private javax.swing.JLabel Lbl_ResCU;
    private javax.swing.JLabel Lbl_ResCUDer_HC;
    private javax.swing.JLabel Lbl_ResGIFDer_HC;
    private javax.swing.JLabel Lbl_ResGIF_HC;
    private javax.swing.JLabel Lbl_ResMDDer_HC;
    private javax.swing.JLabel Lbl_ResMD_HC;
    private javax.swing.JLabel Lbl_ResMODDer_HC;
    private javax.swing.JLabel Lbl_ResMod_HC;
    private javax.swing.JLabel Lbl_SubGIF_HC;
    private javax.swing.JLabel Lbl_SubMD_HC;
    private javax.swing.JLabel Lbl_SubMOD_HC;
    private javax.swing.JPanel LineaArriba_GIF;
    private javax.swing.JPanel LineaArriba_HC;
    private javax.swing.JPanel LineaArriba_InD;
    private javax.swing.JPanel LineaArriba_Req;
    private javax.swing.JPanel LineaArriba_TarjetaT;
    private javax.swing.JPanel Menu_IZQ;
    private javax.swing.JTextField Num_Ped_TT;
    private javax.swing.JPanel Panel_CT_HC;
    private javax.swing.JPanel Pantallas;
    private javax.swing.JPanel Req;
    private javax.swing.JLabel SubT_GIF;
    private javax.swing.JLabel SubT_HC;
    private javax.swing.JLabel SubT_InD;
    private javax.swing.JLabel SubT_Req;
    private javax.swing.JLabel SubT_TarjetaT;
    private javax.swing.JTextField TF_BaseA_GIF;
    private javax.swing.JTextField TF_Cant_InD;
    private javax.swing.JTextField TF_Cliente_InD;
    private javax.swing.JTextField TF_Departamento_Req;
    private javax.swing.JTextField TF_Departamento_Req1;
    private javax.swing.JTextField TF_Departamento_Req2;
    private javax.swing.JTextField TF_DescP_InD;
    private javax.swing.JTextField TF_FechaIn_InD;
    private javax.swing.JTextField TF_FechaTe_InD;
    private javax.swing.JTextField TF_Fecha_Req;
    private javax.swing.JTextField TF_GIFP_GIF;
    private javax.swing.JTextField TF_Mes_TT;
    private javax.swing.JTextField TF_NomEmp_TT;
    private javax.swing.JTextField TF_NumNom_TT;
    private javax.swing.JTextField TF_NumPedido_Req;
    private javax.swing.JTextField TF_NumReq_Req;
    private javax.swing.JScrollPane T_Req;
    private javax.swing.JTable TablaReq;
    private javax.swing.JTable TablaReq1;
    private javax.swing.JTable Tabla_GIF_HC;
    private javax.swing.JTable Tabla_MD_HC;
    private javax.swing.JTable Tabla_MOD_HC;
    private javax.swing.JPanel TarjetaT;
    private javax.swing.JPanel TasaGIF;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
